#!/usr/bin/env node
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import type { IconInfo } from "../src/catalog.ts"
import { readCatalog } from "../src/catalog.ts"

const packageDirectory = fileURLToPath(new URL("../", import.meta.url))
const svgRootPattern = /<svg\b([^>]*)>([\s\S]*?)<\/svg>/
const dimensionPattern = /\s(?:width|height)="[^"]*"/g
const jsxAttributePattern = /\b([\w:-]+)=/g
const kebabAttributePattern = /[-:]([a-z])/g

function jsxAttributes(markup: string): string {
  return markup.replace(jsxAttributePattern, (attribute: string, name: string) => {
    if (name === "class") {
      return "className="
    }
    if (name.startsWith("aria-") || name.startsWith("data-")) {
      return attribute
    }
    return `${name.replace(kebabAttributePattern, (_match: string, letter: string) =>
      letter.toUpperCase()
    )}=`
  })
}

function iconModule(componentName: string, info: IconInfo, svg: string): string {
  const match = svg.match(svgRootPattern)
  if (!match) {
    throw new Error(`Expected an <svg> root for ${componentName} (${info.pack}/${info.svgFile})`)
  }
  const attributes = jsxAttributes(match[1].replace(dimensionPattern, "")).trim()
  const children = jsxAttributes(match[2]).trim()
  return `// Generated from assets/${info.pack}/${info.svgFile} by scripts/generate-icons.ts. Do not edit.
import { iconDimensions, renderIcon, renderInline, type IconProps } from "../runtime/icon.js";

function DevIcon({ size, width, height, ...rest }: IconProps) {
  return (
    <svg
      ${attributes}
      {...rest}
      {...iconDimensions({ size, width, height })}
    >
      ${children}
    </svg>
  );
}

export function ${componentName}(props: IconProps) {
  if (process.env.NODE_ENV !== "production") {
    return renderInline(DevIcon, props);
  }
  return renderIcon("${info.spriteId}", props);
}
`
}

function readAsset(info: IconInfo): string {
  return readFileSync(path.join(packageDirectory, "assets", info.pack, info.svgFile), "utf8")
}

/**
 * Derive React wrappers and local development components from package-owned
 * catalog/assets. Upstream icon packages never participate in ordinary builds.
 */
export function generateIcons(outputDirectory = packageDirectory) {
  const catalog = readCatalog(packageDirectory)
  const output = new Map<string, string>()
  const sourceFiles = new Set<string>()

  for (const [name, info] of Object.entries(catalog)) {
    const svg = readAsset(info)
    sourceFiles.add(`${info.pack}/${info.svgFile}`)
    output.set(`src/icons/${name}.tsx`, iconModule(name, info, svg))
  }

  const exports = Object.keys(catalog)
    .sort((left, right) => left.localeCompare(right))
    .map((name) => `export { ${name} } from "./${name}.js";`)
  output.set(
    "src/icons/index.ts",
    `// Generated by scripts/generate-icons.ts. Do not edit.\n${exports.join("\n")}\n`
  )

  // Finish reading/rendering first. A bad catalog or SVG cannot erase prior output.
  rmSync(path.join(outputDirectory, "src/icons"), { recursive: true, force: true })
  mkdirSync(path.join(outputDirectory, "src/icons"), { recursive: true })
  for (const [file, content] of output) {
    writeFileSync(path.join(outputDirectory, file), content)
  }
  return { icons: Object.keys(catalog).length, sourceSvgs: sourceFiles.size }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { icons, sourceSvgs } = generateIcons()
  console.log(`Generated ${icons} icons from ${sourceSvgs} package-owned SVGs.`)
}
