#!/usr/bin/env node
import { mkdirSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { type IconInfo, writeCatalog } from "../src/catalog.ts"
import { readIconCatalog } from "./icon-catalog.ts"

const packageDir = fileURLToPath(new URL("../", import.meta.url))
const svgRootPattern = /<svg\b([^>]*)>([\s\S]*?)<\/svg>/

function wrapper(componentName: string, { pack, spriteId }: IconInfo): string {
  const devImport =
    pack === "lucide" ? `../lucide-archive/${componentName}.js` : "@tabler/icons-react"
  return `// Generated by scripts/generate-icons.ts. Do not edit.
import { ${componentName} as DevIcon } from "${devImport}";
import { renderIcon, renderInline, type IconProps } from "../runtime/icon.js";

export function ${componentName}(props: IconProps) {
  if (process.env.NODE_ENV !== "production") {
    return renderInline(DevIcon, props);
  }
  return renderIcon("${spriteId}", props);
}
`
}

function jsxAttributes(markup: string): string {
  return markup.replace(/\b([\w:-]+)=/g, (attribute: string, name: string) => {
    if (name === "class") {
      return "className="
    }
    if (name.startsWith("aria-") || name.startsWith("data-")) {
      return attribute
    }
    return `${name.replace(/[-:]([a-z])/g, (_: string, letter: string) => letter.toUpperCase())}=`
  })
}

function archivedComponent(componentName: string, svg: string): string {
  const match = svg.match(svgRootPattern)
  if (!match) {
    throw new Error(`Expected an <svg> root for ${componentName}`)
  }
  const attributes = jsxAttributes(match[1].replace(/\s(?:width|height)="[^"]*"/g, "")).trim()
  const children = jsxAttributes(match[2]).trim()
  return `// Generated from assets/lucide by scripts/generate-icons.ts. Do not edit.
import { iconDimensions, type IconProps } from "../runtime/icon.js";

export function ${componentName}({ size, width, height, ...rest }: IconProps) {
  return (
    <svg
      ${attributes}
      {...rest}
      {...iconDimensions({ size, width, height })}
    >
      ${children}
    </svg>
  );
}
`
}

/**
 * Regenerate wrappers, local Lucide components, the icon barrel and CLI data.
 * Reads the archive without updating it; outputDir defaults to this package,
 * independent of the working directory. Only generated paths are replaced.
 */
export function generateIcons(outputDir = packageDir) {
  const { mapping, lucideSvgs, skippedIcons } = readIconCatalog()
  const output = new Map<string, string>()
  for (const [name, info] of Object.entries(mapping)) {
    output.set(`src/icons/${name}.tsx`, wrapper(name, info))
    if (info.pack === "lucide") {
      output.set(
        `src/lucide-archive/${name}.tsx`,
        archivedComponent(name, lucideSvgs[info.svgFile])
      )
    }
  }
  const exports = Object.keys(mapping)
    .sort()
    .map((name) => `export { ${name} } from "./${name}.js";`)
  output.set(
    "src/icons/index.ts",
    `// Generated by scripts/generate-icons.ts. Do not edit.\n${exports.join("\n")}\n`
  )
  output.set("generated/skipped-icons.json", `${JSON.stringify(skippedIcons, null, 2)}\n`)

  // Finish reading and rendering before removing the previous generated files.
  for (const directory of ["src/icons", "src/lucide-archive"]) {
    rmSync(path.join(outputDir, directory), { recursive: true, force: true })
    mkdirSync(path.join(outputDir, directory), { recursive: true })
  }
  mkdirSync(path.join(outputDir, "generated"), { recursive: true })
  for (const [file, content] of output) {
    writeFileSync(path.join(outputDir, file), content)
  }
  writeCatalog(outputDir, { mapping, lucideSvgs })
  return {
    icons: Object.keys(mapping).length,
    archivedSvgs: Object.keys(lucideSvgs).length,
    skipped: skippedIcons.length,
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { icons, archivedSvgs, skipped } = generateIcons()
  console.log(
    `Generated ${icons} icons, ${archivedSvgs} archived SVGs and ${skipped} collision records.`
  )
}
