#!/usr/bin/env node
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { IconInfo } from "../src/icon-info.js";
import { readIconCatalog } from "./icon-catalog.ts";

const packageDir = fileURLToPath(new URL("../", import.meta.url));

function wrapper(componentName: string, { pack, spriteId }: IconInfo): string {
  const devImport = pack === "lucide" ? `../lucide-archive/${componentName}.js` : "@tabler/icons-react";
  return `// Generated by scripts/generate-icons.ts. Do not edit.
import { SPRITE_PATH } from "../config.js";
import { ${componentName} as DevIcon } from "${devImport}";
import { renderUse, type IconProps } from "../render-use.js";

export function ${componentName}(props: IconProps) {
  if (process.env.NODE_ENV !== "production") {
    const { size, width, height, ...rest } = props;
    return (
      <DevIcon
        {...rest}
        size={size ?? 24}
        {...(width != null ? { width } : {})}
        {...(height != null ? { height } : {})}
      />
    );
  }
  return renderUse("${spriteId}", SPRITE_PATH, props);
}
`;
}

function jsxAttributes(markup: string): string {
  return markup.replace(/\b([\w:-]+)=/g, (attribute: string, name: string) => {
    if (name === "class") return "className=";
    if (name.startsWith("aria-") || name.startsWith("data-")) return attribute;
    return `${name.replace(/[-:]([a-z])/g, (_: string, letter: string) => letter.toUpperCase())}=`;
  });
}

function archivedComponent(componentName: string, svg: string): string {
  const match = svg.match(/<svg\b([^>]*)>([\s\S]*?)<\/svg>/);
  if (!match) throw new Error(`Expected an <svg> root for ${componentName}`);
  const attributes = jsxAttributes(match[1].replace(/\s(?:width|height)="[^"]*"/g, "")).trim();
  const children = jsxAttributes(match[2]).trim();
  return `// Generated from assets/lucide by scripts/generate-icons.ts. Do not edit.
import { type IconProps } from "../render-use.js";

export function ${componentName}({ size, width, height, ...rest }: IconProps) {
  return (
    <svg
      ${attributes}
      {...rest}
      width={width ?? size ?? 24}
      height={height ?? size ?? 24}
    >
      ${children}
    </svg>
  );
}
`;
}

/**
 * Regenerate wrappers, local Lucide components, the source barrel and CLI data.
 * Reads the archive without updating it; outputDir defaults to this package,
 * independent of the working directory. Only generated paths are replaced.
 */
export function generateIcons(outputDir = packageDir) {
  const { mapping, lucideSvgs, skippedIcons } = readIconCatalog();
  const output = new Map<string, string>();
  for (const [name, info] of Object.entries(mapping)) {
    output.set(`src/icons/${name}.tsx`, wrapper(name, info));
    if (info.pack === "lucide") {
      output.set(`src/lucide-archive/${name}.tsx`, archivedComponent(name, lucideSvgs[info.svgFile]));
    }
  }
  const exports = Object.keys(mapping)
    .sort()
    .map((name) => `export { ${name} } from "./icons/${name}.js";`);
  exports.push('export { CustomIcon } from "./custom-icon.js";');
  exports.push('export type { IconProps } from "./render-use.js";');
  exports.push('export type { ZeroUIConfig } from "./config.js";');
  output.set("src/index.ts", `// Generated by scripts/generate-icons.ts. Do not edit.\n${exports.join("\n")}\n`);
  output.set("generated/component-sprite-map.json", `${JSON.stringify(mapping, null, 2)}\n`);
  output.set("generated/lucide-icons.json", `${JSON.stringify(lucideSvgs)}\n`);
  output.set("generated/skipped-icons.json", `${JSON.stringify(skippedIcons, null, 2)}\n`);

  // Finish reading and rendering before removing the previous generated files.
  for (const directory of ["src/icons", "src/lucide-archive"]) {
    rmSync(path.join(outputDir, directory), { recursive: true, force: true });
    mkdirSync(path.join(outputDir, directory), { recursive: true });
  }
  mkdirSync(path.join(outputDir, "generated"), { recursive: true });
  for (const [file, content] of output) writeFileSync(path.join(outputDir, file), content);
  return {
    icons: Object.keys(mapping).length,
    archivedSvgs: Object.keys(lucideSvgs).length,
    skipped: skippedIcons.length,
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { icons, archivedSvgs, skipped } = generateIcons();
  console.log(`Generated ${icons} icons, ${archivedSvgs} archived SVGs and ${skipped} collision records.`);
}
