import { copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { ICON_CATALOG_FILE, type IconInfo } from "../../icon-sprite/src/build/icon-data-format.ts"
import { readCanonicalCatalog, readCanonicalSvg, writePackagedIconData } from "./catalog.ts"

const libraryDirectory = fileURLToPath(new URL("../", import.meta.url))
const defaultOutputDirectory = fileURLToPath(new URL("../../icon-sprite/", import.meta.url))
const svgRootPattern = /<svg\b([^>]*)>([\s\S]*?)<\/svg>/
const omittedRootAttributePattern = /\s(?:class|width|height)=(["'])[^"']*\1/g
const jsxAttributePattern = /\b([\w:-]+)=/g
const kebabAttributePattern = /[-:]([a-z])/g

function jsxAttributes(markup: string): string {
  return markup.replace(jsxAttributePattern, (attribute: string, name: string) => {
    if (name === "class") {
      return "className="
    }
    if (name.startsWith("aria-") || name.startsWith("data-")) {
      return attribute
    }
    return `${name.replace(kebabAttributePattern, (_match: string, letter: string) =>
      letter.toUpperCase()
    )}=`
  })
}

function createIconComponentSource(componentName: string, info: IconInfo, svg: string): string {
  const match = svg.match(svgRootPattern)
  if (!match) {
    throw new Error(`Expected an <svg> root for ${componentName} (${info.pack}/${info.svgFile})`)
  }
  const attributes = jsxAttributes(match[1].replace(omittedRootAttributePattern, "")).trim()
  const children = jsxAttributes(match[2]).trim()
  return `// Generated from assets/${info.pack}/${info.svgFile} by icon-library/component-generation.ts. Do not edit.
import { resolveIconDimensions, renderProdIcon, type IconProps } from "../react/icon.js";

function DevIcon({ size, width, height, ...rest }: IconProps) {
  return (
    <svg
      ${attributes}
      aria-hidden="true"
      {...rest}
      {...resolveIconDimensions({ size, width, height })}
    >
      ${children}
    </svg>
  );
}

export function ${componentName}(props: IconProps) {
  if (process.env.NODE_ENV !== "production") {
    return <DevIcon {...props} />;
  }
  return renderProdIcon("${info.spriteId}", props);
}
`
}

/**
 * Derive React wrappers and local development components from package-owned
 * catalog/assets. Upstream icon packages never participate in ordinary builds.
 */
export function generateIconComponents(outputDirectory = defaultOutputDirectory) {
  const catalog = readCanonicalCatalog(libraryDirectory)
  const output = new Map<string, string>()
  const sourceFiles = new Set<string>()

  for (const [name, info] of Object.entries(catalog)) {
    const svg = readCanonicalSvg(info, libraryDirectory)
    sourceFiles.add(`${info.pack}/${info.svgFile}`)
    output.set(`src/icons/${name}.tsx`, createIconComponentSource(name, info, svg))
  }

  const exports = Object.keys(catalog)
    .sort((left, right) => left.localeCompare(right))
    .map((name) => `export { ${name} } from "./${name}.js";`)
  output.set(
    "src/icons/index.ts",
    `// Generated by icon-library/component-generation.ts. Do not edit.\n${exports.join("\n")}\n`
  )

  // Finish reading/rendering first. A bad catalog or SVG cannot erase prior output.
  rmSync(path.join(outputDirectory, "src/icons"), { recursive: true, force: true })
  mkdirSync(path.join(outputDirectory, "src/icons"), { recursive: true })
  for (const [file, content] of output) {
    writeFileSync(path.join(outputDirectory, file), content)
  }
  return { icons: Object.keys(catalog).length, sourceSvgs: sourceFiles.size }
}

function copyPackageAssets(outputDirectory: string): void {
  const assets = path.join(outputDirectory, "assets")
  const licenses = path.join(assets, "licenses")
  mkdirSync(licenses, { recursive: true })
  copyFileSync(
    path.join(libraryDirectory, ICON_CATALOG_FILE),
    path.join(outputDirectory, ICON_CATALOG_FILE)
  )
  for (const pack of ["lucide", "tabler"]) {
    copyFileSync(
      path.join(libraryDirectory, "assets/licenses", `${pack}.txt`),
      path.join(licenses, `${pack}.txt`)
    )
  }
}

/**
 * Generate every repository-owned input required to build and pack icon-sprite.
 * Canonical state stays in this private workspace; the published package receives
 * only generated React source, package-ready catalog/licenses, and bundled SVG data.
 */
export function generateIconPackage(outputDirectory = defaultOutputDirectory) {
  const components = generateIconComponents(outputDirectory)
  copyPackageAssets(outputDirectory)
  const packagedSvgs = writePackagedIconData(outputDirectory, libraryDirectory)
  return { ...components, packagedSvgs }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = generateIconPackage()
  console.log(
    `Generated ${result.icons} icons from ${result.sourceSvgs} canonical SVGs and packaged ${result.packagedSvgs} SVG assets.`
  )
}
